namespace JPDataExchange.EnumAdvanced.TestSample
{
    enum LeaveReasons
    {
        [Eligible(EligibleForVSCashOutDuringLOA.No)]
        [ReferenceID("LEAVE_TYPE_REASON-6-1")]
        LEAVE_TYPE_REASON_6_1,
        [Eligible(EligibleForVSCashOutDuringLOA.Yes)]
        [ReferenceID("LEAVE_TYPE_REASON-6-2")]
        LEAVE_TYPE_REASON_6_2,
        [Eligible(EligibleForVSCashOutDuringLOA.No)]
        [ReferenceID("LEAVE_TYPE_REASON-6-3")]
        LEAVE_TYPE_REASON_6_3,
        [Eligible(EligibleForVSCashOutDuringLOA.Yes)]
        [ReferenceID("LEAVE_TYPE_REASON-6-4")]
        LEAVE_TYPE_REASON_6_4,
        [Eligible(EligibleForVSCashOutDuringLOA.No)]
        [ReferenceID("LEAVE_TYPE_REASON-6-5")]
        LEAVE_TYPE_REASON_6_5,
        [Eligible(EligibleForVSCashOutDuringLOA.Yes)]
        [ReferenceID("LEAVE_TYPE_REASON-6-6")]
        LEAVE_TYPE_REASON_6_6,
        [Eligible(EligibleForVSCashOutDuringLOA.No)]
        [ReferenceID("LEAVE_TYPE_REASON-6-7")]
        LEAVE_TYPE_REASON_6_7,
        [Eligible(EligibleForVSCashOutDuringLOA.Yes)]
        [ReferenceID("LEAVE_TYPE_REASON-6-8")]
        LEAVE_TYPE_REASON_6_8,
        [Eligible(EligibleForVSCashOutDuringLOA.No)]
        [ReferenceID("LEAVE_TYPE_REASON-6-9")]
        LEAVE_TYPE_REASON_6_9,
        [Eligible(EligibleForVSCashOutDuringLOA.Yes)]
        [ReferenceID("LEAVE_TYPE_REASON-6-10")]
        LEAVE_TYPE_REASON_6_10,
        [Eligible(EligibleForVSCashOutDuringLOA.No)]
        [ReferenceID("LEAVE_TYPE_REASON-6-11")]
        LEAVE_TYPE_REASON_6_11,
        [Eligible(EligibleForVSCashOutDuringLOA.Yes)]
        [ReferenceID("LEAVE_TYPE_REASON-6-12")]
        LEAVE_TYPE_REASON_6_12,
        [Eligible(EligibleForVSCashOutDuringLOA.No)]
        [ReferenceID("LEAVE_TYPE_REASON-6-13")]
        LEAVE_TYPE_REASON_6_13,
        [Eligible(EligibleForVSCashOutDuringLOA.Yes)]
        [ReferenceID("LEAVE_TYPE_REASON-6-14")]
        LEAVE_TYPE_REASON_6_14,
        [Eligible(EligibleForVSCashOutDuringLOA.No)]
        [ReferenceID("LEAVE_TYPE_REASON-6-15")]
        LEAVE_TYPE_REASON_6_15,
        [Eligible(EligibleForVSCashOutDuringLOA.Yes)]
        [ReferenceID("LEAVE_TYPE_REASON-6-16")]
        LEAVE_TYPE_REASON_6_16,
        [Eligible(EligibleForVSCashOutDuringLOA.No)]
        [ReferenceID("LEAVE_TYPE_REASON-6-17")]
        LEAVE_TYPE_REASON_6_17,
        [Eligible(EligibleForVSCashOutDuringLOA.Yes)]
        [ReferenceID("LEAVE_TYPE_REASON-6-18")]
        LEAVE_TYPE_REASON_6_18,
        [Eligible(EligibleForVSCashOutDuringLOA.No)]
        [ReferenceID("LEAVE_TYPE_REASON-6-19")]
        LEAVE_TYPE_REASON_6_19,
        [Eligible(EligibleForVSCashOutDuringLOA.Yes)]
        [ReferenceID("LEAVE_TYPE_REASON-6-20")]
        LEAVE_TYPE_REASON_6_20,
        [Eligible(EligibleForVSCashOutDuringLOA.No)]
        [ReferenceID("LEAVE_TYPE_REASON-6-21")]
        LEAVE_TYPE_REASON_6_21,
        [Eligible(EligibleForVSCashOutDuringLOA.Yes)]
        [ReferenceID("LEAVE_TYPE_REASON-6-22")]
        LEAVE_TYPE_REASON_6_22,
        [Eligible(EligibleForVSCashOutDuringLOA.No)]
        [ReferenceID("LEAVE_TYPE_REASON-6-23")]
        LEAVE_TYPE_REASON_6_23,
        [Eligible(EligibleForVSCashOutDuringLOA.Yes)]
        [ReferenceID("LEAVE_TYPE_REASON-6-24")]
        LEAVE_TYPE_REASON_6_24,
        [Eligible(EligibleForVSCashOutDuringLOA.No)]
        [ReferenceID("LEAVE_TYPE_REASON-6-25")]
        LEAVE_TYPE_REASON_6_25,
        [Eligible(EligibleForVSCashOutDuringLOA.Yes)]
        [ReferenceID("LEAVE_TYPE_REASON-6-26")]
        LEAVE_TYPE_REASON_6_26,
        [Eligible(EligibleForVSCashOutDuringLOA.No)]
        [ReferenceID("LEAVE_TYPE_REASON-6-27")]
        LEAVE_TYPE_REASON_6_27,
        [Eligible(EligibleForVSCashOutDuringLOA.Yes)]
        [ReferenceID("LEAVE_TYPE_REASON-6-28")]
        LEAVE_TYPE_REASON_6_28,
        [Eligible(EligibleForVSCashOutDuringLOA.No)]
        [ReferenceID("LEAVE_TYPE_REASON-6-29")]
        LEAVE_TYPE_REASON_6_29,
        [Eligible(EligibleForVSCashOutDuringLOA.Yes)]
        [ReferenceID("LEAVE_TYPE_REASON-6-30")]
        LEAVE_TYPE_REASON_6_30,
        [Eligible(EligibleForVSCashOutDuringLOA.No)]
        [ReferenceID("LEAVE_TYPE_REASON-6-31")]
        LEAVE_TYPE_REASON_6_31,
        [Eligible(EligibleForVSCashOutDuringLOA.Yes)]
        [ReferenceID("LEAVE_TYPE_REASON-6-32")]
        LEAVE_TYPE_REASON_6_32,
        [Eligible(EligibleForVSCashOutDuringLOA.No)]
        [ReferenceID("LEAVE_TYPE_REASON-6-33")]
        LEAVE_TYPE_REASON_6_33,
        [Eligible(EligibleForVSCashOutDuringLOA.Yes)]
        [ReferenceID("LEAVE_TYPE_REASON-6-34")]
        LEAVE_TYPE_REASON_6_34,
        [Eligible(EligibleForVSCashOutDuringLOA.No)]
        [ReferenceID("LEAVE_TYPE_REASON-6-35")]
        LEAVE_TYPE_REASON_6_35,
        [Eligible(EligibleForVSCashOutDuringLOA.Yes)]
        [ReferenceID("LEAVE_TYPE_REASON-6-36")]
        LEAVE_TYPE_REASON_6_36,
        [Eligible(EligibleForVSCashOutDuringLOA.No)]
        [ReferenceID("LEAVE_TYPE_REASON-6-37")]
        LEAVE_TYPE_REASON_6_37,
        [Eligible(EligibleForVSCashOutDuringLOA.Yes)]
        [ReferenceID("LEAVE_TYPE_REASON-6-38")]
        LEAVE_TYPE_REASON_6_38,
        [Eligible(EligibleForVSCashOutDuringLOA.No)]
        [ReferenceID("LEAVE_TYPE_REASON-6-39")]
        LEAVE_TYPE_REASON_6_39,
        [Eligible(EligibleForVSCashOutDuringLOA.Yes)]
        [ReferenceID("LEAVE_TYPE_REASON-6-40")]
        LEAVE_TYPE_REASON_6_40,
        [Eligible(EligibleForVSCashOutDuringLOA.No)]
        [ReferenceID("LEAVE_TYPE_REASON-6-41")]
        LEAVE_TYPE_REASON_6_41,
        [Eligible(EligibleForVSCashOutDuringLOA.Yes)]
        [ReferenceID("LEAVE_TYPE_REASON-6-42")]
        LEAVE_TYPE_REASON_6_42,
        [Eligible(EligibleForVSCashOutDuringLOA.No)]
        [ReferenceID("LEAVE_TYPE_REASON-6-43")]
        LEAVE_TYPE_REASON_6_43,
        [Eligible(EligibleForVSCashOutDuringLOA.Yes)]
        [ReferenceID("LEAVE_TYPE_REASON-6-44")]
        LEAVE_TYPE_REASON_6_44,
        [Eligible(EligibleForVSCashOutDuringLOA.No)]
        [ReferenceID("LEAVE_TYPE_REASON-6-45")]
        LEAVE_TYPE_REASON_6_45,
        [Eligible(EligibleForVSCashOutDuringLOA.Yes)]
        [ReferenceID("LEAVE_TYPE_REASON-6-46")]
        LEAVE_TYPE_REASON_6_46,
        [Eligible(EligibleForVSCashOutDuringLOA.No)]
        [ReferenceID("LEAVE_TYPE_REASON-6-47")]
        LEAVE_TYPE_REASON_6_47,
        [Eligible(EligibleForVSCashOutDuringLOA.Yes)]
        [ReferenceID("LEAVE_TYPE_REASON-6-48")]
        LEAVE_TYPE_REASON_6_48,
        [Eligible(EligibleForVSCashOutDuringLOA.No)]
        [ReferenceID("LEAVE_TYPE_REASON-6-49")]
        LEAVE_TYPE_REASON_6_49,
        [Eligible(EligibleForVSCashOutDuringLOA.Yes)]
        [ReferenceID("LEAVE_TYPE_REASON-6-50")]
        LEAVE_TYPE_REASON_6_50,
        [Eligible(EligibleForVSCashOutDuringLOA.No)]
        [ReferenceID("LEAVE_TYPE_REASON-6-51")]
        LEAVE_TYPE_REASON_6_51,
        [Eligible(EligibleForVSCashOutDuringLOA.Yes)]
        [ReferenceID("LEAVE_TYPE_REASON-6-52")]
        LEAVE_TYPE_REASON_6_52,
        [Eligible(EligibleForVSCashOutDuringLOA.No)]
        [ReferenceID("LEAVE_TYPE_REASON-6-53")]
        LEAVE_TYPE_REASON_6_53,
        [Eligible(EligibleForVSCashOutDuringLOA.Yes)]
        [ReferenceID("LEAVE_TYPE_REASON-6-54")]
        LEAVE_TYPE_REASON_6_54,
        [Eligible(EligibleForVSCashOutDuringLOA.No)]
        [ReferenceID("LEAVE_TYPE_REASON-6-55")]
        LEAVE_TYPE_REASON_6_55,
        [Eligible(EligibleForVSCashOutDuringLOA.Yes)]
        [ReferenceID("LEAVE_TYPE_REASON-6-56")]
        LEAVE_TYPE_REASON_6_56,
        [Eligible(EligibleForVSCashOutDuringLOA.No)]
        [ReferenceID("LEAVE_TYPE_REASON-6-57")]
        LEAVE_TYPE_REASON_6_57,
        [Eligible(EligibleForVSCashOutDuringLOA.Yes)]
        [ReferenceID("LEAVE_TYPE_REASON-6-58")]
        LEAVE_TYPE_REASON_6_58
    }
}
